### PR TITLE
Add pow for dec128

### PR DESCRIPTION
**Pull request by trolleyman**
Ok, this should be [better](https://github.com/alkis/decimal/pull/5) now.

[Review on Reviewable](https://reviewable.io/reviews/alkis/decimal/6)

### CODE REVIEW

**Comment by alkis** [comment]
Thanks for the contribution! It is very much appreciated. Please address the following comments.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/dec128.rs, line 29 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XFyTElZgv_EDg_4aT:-K5XFyTElZgv_EDg_4aU:-360461635) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L29)):*
Let's skip the struct comments. They are not interesting to the decimal library reader.

---

*[src/dec128.rs, line 34 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XIO2r0RkTCb4CgJOR:-K5XIO2r0RkTCb4CgJOS:724196796) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L34)):*
This is the only one that needs a comment. Here's what I think should go here:

```rust
// DECPUN = 3 because this is the fastest for conversion between decNumber and decQuad
// DECNUMDIGITS = 34 because we use decQuad only
// 12 = ((DECNUMDIGITS+DECDPUN-1)/DECDPUN)
```

Also because we set this to 12 we need to set DECNUMDIGITS to 34 when compiling decNumber library (see build.rs) otherwise when you call decimal128ToNumber the decNumber library thinks there is only 1 u16 at the end of the struct so it will allocate something on the heap to perform pow. Because we know exactly how many digits we have, we can avoid this allocation.

---

*[src/dec128.rs, line 440 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XGFhx6DdMsY3wl3vt:-K5XGFhykof4ltc_gR-Z:-1137309614) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L440)):*
Let's plagiarize the documentation from [decNumberPower](http://speleotrove.com/decimal/dnnumb.html#dnpower).

What I do is cut and paste it, adapt it for decQuad, rename the variables (there is no lhs and rhs in our implementation) and then reflow (if you are using Atom editor ctrl-alt-q).

---

*[src/dec128.rs, line 441 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XGwPm5FgD3L2wi8eZ:-K5XGwPm5FgD3L2wi8e_:1228041908) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L441)):*
I think there are trailing spaces at the end of ///. Please remove them.

---

*[src/dec128.rs, line 455 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XH1Ab5xveG0X_-cLi:-K5XH1Ab5xveG0X_-cLj:-1735704155) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L455)):*
Please use rustfmt for the code formatting. It makes everything consistent and it is really easy to do.

```bash
cargo install --git https://github.com/rust-lang-nursery/rustfmt
```

Then ~/.cargo/bin/rustfmt _filename_

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alkis/decimal/6#-:-K5XJWILtNUYCZXWLQt5:-194560249)*

**Comment by trolleyman** [comment]
Done.

**Comment by alkis** [comment]
Thank you! It looks really good. Only one thing left, the change to build.rs to make sure You missed the change to build.rs (see comment below). Otherwise it looks really good.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/dec128.rs, line 34 \[r1\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XIO2r0RkTCb4CgJOR:-K5XuTpmK_9mRauFmHxk:-1046621233) ([raw file](https://github.com/alkis/decimal/blob/529867fb2128de708bb0a61791448f201c599f97/src/dec128.rs#L34)):*
Modification to build.rs is still pending.  You need to add a single call after .include():

```rust
.define("DECNUMDIGITS", Some("34"))
```

---

*[src/dec128.rs, line 28 \[r2\]](https://reviewable.io:443/reviews/alkis/decimal/6#-K5XvSq_e3AkSgS7n2ZU:-K5XvSq_e3AkSgS7n2ZV:1698761892) ([raw file](https://github.com/alkis/decimal/blob/2400310f55cc346695b52b80670170a21786146a/src/dec128.rs#L28)):*
Also I just noticed this. Let's name this decNumber (first letter lower case) to match the one in the C file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/alkis/decimal/6#-:-K5Xv4gulzogAm43Ku6K:705035744)*

**Comment by trolleyman** [comment]
This ok? Oh and I was wondering about [constants](https://github.com/alkis/decimal/issues/7)...

**Comment by alkis** [comment]
Thanks for the patch and going through the code review!

**Pull request merged**
