### PR TITLE
Adding Hash Implementation

### PR DESCRIPTION
**Pull request by MarkJr94**
Fixes Issue #17 

I don't know whether the version in Cargo.toml should be bumped or anything, I left that up to you.

### CODE REVIEW

**Comment by MarkJr94** [comment]
I also added serialization from serde while I was at at it.

**Comment by alkis** [comment]
Thanks for the contribution!

Is it possible to split the two in two different PRs? One for Hash and one for serde.

**Comment by MarkJr94** [comment]
It should be possible, I am working on it right now, and will make new PR(s) ASAP

**Comment by MarkJr94** [comment]
superseded by PR #19  and PR #20

**Pull request closed without merging**
